spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deliverium
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: myatlay29198@gmail.com
    password: zhaqapsviunnvkuv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8000
  servlet:
    session:
      timeout: 30m
